### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by zer0Kerbal** [drewcassidy/yaclog-ksp#1]
This is what I am feeding it:
[_1.3.99.2-beta.md](https://github.com/drewcassidy/yaclog-ksp/files/7316578/_1.3.99.2-beta.md)

which is being generated by batch file

this is how I am calling it: (the input file is located in a subfolder named _ReleaseNotes)
`yaclog-ksp --path _ReleaseNotes\_1.3.99.2-beta.md --name Kaboom`

this is what it spits out:

> `Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\yaclog-ksp.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\yaclog_ksp\__main__.py", line 42, in main
    name = segments[0] + [' ' + s for s in segments[1:]]
TypeError: can only concatenate str (not "list") to str`

[KaboomChangeLog.zip](https://github.com/drewcassidy/yaclog-ksp/files/7316586/KaboomChangeLog.zip)

**Comment by zer0Kerbal** [comment]
it also seems to fail when \Versioning\ is not present.

**Comment by zer0Kerbal** [comment]
never mind - found the error(s)
date format - and needed additional #'s
[_ReleaseNotes.zip](https://github.com/drewcassidy/yaclog-ksp/files/7316814/_ReleaseNotes.zip)
here is the new input / output
